### ISSUE TITLE
Show Anvil window on launch

### ISSUE THREAD

**Issue by elliottkember** [beachio/anvilformac#3]
But make sure it doesn't open on Login!!!111

**Comment by pbrocker** [comment]
@elliottkember: This seems like a personal preference. Anvil will autostart all your apps if they are not running already. So why would there be a need to show the Anvil window? Only reason I see showing it is if there are no apps/projects in Anvil. Maybe then on launch we could show it. Thoughts?

**Comment by elliottkember** [comment]
Hey. This was a personal preference because I built Anvil. When starting a menu bar app, many users don't know it's started because nothing shows up and they complain about it. 

But again this is a 3-year old issue like all the others and I don't work on or use Anvil any more.
