### ISSUE TITLE
Anvil won't add a site twice

### ISSUE THREAD

**Issue by elliottkember** [beachio/anvilformac#5]
Lame!

**Comment by pbrocker** [comment]
@elliotkember: why would you want to add the same site twice? if sites are not uniquely named (so there a duplicate names). Then anvil will not be able to determine which site is which. Mac/Windows/Linux does not allow you to have duplicate file/folder names. So why should anvil?

**Comment by pbrocker** [comment]
if you are trying to rename a site (or have renamed the folder). then you should delete your site and then re-add it. If you are trying to add a site with the same name. Then anvil only allowing one of that site (name) is the expected behavior.

**Comment by elliottkember** [comment]
Hi. I don't think you know this but I was the original author of Anvil. These issues are over three years old and can all be closed. 

In this case, a user wanted two domains to point to the same site. Not unreasonable and certainly possible.
