### ISSUE TITLE
Build folder capital letter

### ISSUE THREAD

**Issue by elliottkember** [beachio/anvilformac#6]
One thing that just came to mind that stumps me every now and again, is moving the Build folder to Anvil will fail until you set the Build name to lowercase. After that it works - but a bit of a hidden "gotcha".

**Comment by pbrocker** [comment]
@elliottkember: looking at the code it seems like if the 'Build' folder was capitalized it would work, but if it was lowercase or spelled any other way it would fail. Anvil will now lowercase the build folder when checking for it. See PR (https://github.com/beachio/anvilformac/pull/15)
