### ISSUE TITLE
Anvil uses folder name rather than Hammer project name

### ISSUE THREAD

**Issue by elliottkember** [beachio/anvilformac#8]

**Comment by pbrocker** [comment]
@elliottkember: Anvil relies on pow to declare URL names. When installing powrc you must set up a symlink to your project folder. My guess is when you rename the hammer project the symlink in ~/.pow/ is not getting updated to the new project name. So it is staying as prototype. This is just a guess. I am not a Hammer user.

**Comment by elliottkember** [comment]
This was for the Hammer integration feature I was building at the time. Anvil integrates with Hammer in a special way.
